export const API_ERROR = 'API_ERROR';
export const API_SUCCESS = 'API_SUCCESS';

export const GET_VIDEOS = 'GET_VIDEOS';
export const GET_VIDEO_COMMENTS = 'GET_VIDEO_COMMENTS';
export const VIDEO_LAUGHED_SUCCESS = 'VIDEO_LAUGHED_SUCCESS';
export const POST_VIDEO_COMMENT_SUCCESS = 'POST_VIDEO_COMMENT';
export const COMMENT_LIKED_SUCCESS = 'COMMENT_LIKED_SUCCESS';

export const GET_DIRECT_MESSAGES_DASHBOARD = 'GET_DIRECT_MESSAGES_DASHBOARD';
export const GET_DIRECT_MESSAGES = 'GET_DIRECT_MESSAGES';

export const USER_LOGGED_IN_SUCCESS = 'USER_LOGGED_IN_SUCCESS';
export const USER_LOGGED_OUT_SUCCESS = 'USER_LOGGED_OUT_SUCCESS';

export const SET_SETTINGS_NOTIFICATIONS = 'SET_SETTINGS_NOTIFICATIONS';

export const GET_TRANDING_VIDEOS = 'GET_TRANDING_VIDEOS';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';

export const ADD_USER_SUCCESS = 'ADD_USER_SUCCESS';
