
export const GET_VIDEOS = 'GET_VIDEOS';
export const GET_VIDEO_COMMENTS = 'GET_VIDEO_COMMENTS';

export const GET_DIRECT_MESSAGES_DASHBOARD = 'GET_DIRECT_MESSAGES_DASHBOARD';
export const GET_DIRECT_MESSAGES = 'GET_DIRECT_MESSAGES';

export const USER_LOGGED_IN_SUCCESS = 'USER_LOGGED_IN_SUCCESS';
export const USER_LOGGED_OUT_SUCCESS = 'USER_LOGGED_OUT_SUCCESS';

export const SET_SETTINGS_NOTIFICATIONS = 'SET_SETTINGS_NOTIFICATIONS';